# ---------------------- stage-1 -----------------

# get the base image
FROM node:22 AS builder

# get the working directory
WORKDIR /app

# copy the packages
COPY package*.json ./

# install packages
RUN npm install

# --------------- Stage-2 -------------------

# get the lite-weight base image
FROM node:22-alpine AS runner

# get the working directory
WORKDIR /app

# ---->  /app/node_modules → source folder inside the builder stage
# ---->  ./node_modules → destination folder inside the final runner image

COPY --from=builder /app/node_modules ./node_modules

# get the code
COPY package*.json ./
COPY app.js ./

# exposing port
EXPOSE 3000

# run the main app
CMD ["npm","start"]

